name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Create environment files
        run: |
          touch ./memoryland/src/environments/environment.ts;
          touch ./memoryland/src/environments/environment.prod.ts;
          tree;

      - name: Set environment variables in Angular
        run: |
          echo "// `ng build` replaces \`environment.prod.ts\` with \`environment.prod.ts\`." > src/environments/environment.prod.ts
          echo "const b2cPolicies = {" >> src/environments/environment.prod.ts
          echo "  names: {" >> src/environments/environment.prod.ts
          echo "    signUpSignIn: '${{ secrets.B2C_SIGNUP_SIGNIN_FLOW }}'," >> src/environments/environment.prod.ts
          echo "    editProfile: '${{ secrets.B2C_EDIT_PROFILE_FLOW }}'" >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo "  authorities: {" >> src/environments/environment.prod.ts
          echo "    signUpSignIn: {" >> src/environments/environment.prod.ts
          echo "      authority: '${{ secrets.B2C_SIGNUP_SIGNIN_AUTHORITY }}'" >> src/environments/environment.prod.ts
          echo "    }," >> src/environments/environment.prod.ts
          echo "    editProfile: {" >> src/environments/environment.prod.ts
          echo "      authority: '${{ secrets.B2C_EDIT_PROFILE_AUTHORITY }}'" >> src/environments/environment.prod.ts
          echo "    }" >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo "  authorityDomain: '${{ secrets.B2C_AUTHORITY_DOMAIN }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts
          echo "" >> src/environments/environment.prod.ts
          echo "export const environment = {" >> src/environments/environment.prod.ts
          echo "  production: false," >> src/environments/environment.prod.ts
          echo "  b2cPolicies: b2cPolicies," >> src/environments/environment.prod.ts
          echo "  msalConfig: {" >> src/environments/environment.prod.ts
          echo "    auth: {" >> src/environments/environment.prod.ts
          echo "      clientId: '${{ secrets.CLIENT_ID }}'," >> src/environments/environment.prod.ts
          echo "      authority: b2cPolicies.authorities.signUpSignIn.authority," >> src/environments/environment.prod.ts
          echo "      knownAuthorities: [b2cPolicies.authorityDomain]," >> src/environments/environment.prod.ts
          echo "      redirectUri: '/'," >> src/environments/environment.prod.ts
          echo "    }" >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo "  apiConfig: {" >> src/environments/environment.prod.ts
          echo "    scopes: [" >> src/environments/environment.prod.ts
          echo "      '${{ secrets.SCOPE_READ }}'," >> src/environments/environment.prod.ts
          echo "      '${{ secrets.SCOPE_WRITE }}'" >> src/environments/environment.prod.ts
          echo "    ]," >> src/environments/environment.prod.ts
          echo "    uri: '${{ secrets.BACKEND_URI }}'" >> src/environments/environment.prod.ts
          echo "  }" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DESERT_0ADE3201E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/memoryland" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/memoryland/browser" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DESERT_0ADE3201E }}
          action: "close"
