name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch: # Manually trigger the workflow from the Actions tab
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Create environment files
        run: |
          touch ./memoryland/src/environments/environment.ts;
          touch ./memoryland/src/environments/environment.prod.ts;
          tree;

      - name: Set environment variables in Angular
        run: |
          cat <<EOL > memoryland/src/environments/environment.prod.ts
          const b2cPolicies = {
            names: {
              signUpSignIn: '${{ secrets.B2C_SIGNUP_SIGNIN_FLOW }}',
              editProfile: '${{ secrets.B2C_EDIT_PROFILE_FLOW }}'
            },
            authorities: {
              signUpSignIn: {
                authority: '${{ secrets.B2C_SIGNUP_SIGNIN_AUTHORITY }}'
              },
              editProfile: {
                authority: '${{ secrets.B2C_EDIT_PROFILE_AUTHORITY }}'
              }
            },
            authorityDomain: '${{ secrets.B2C_AUTHORITY_DOMAIN }}'
          };

          export const environment = {
            production: true,
            b2cPolicies: b2cPolicies,
            msalConfig: {
              auth: {
                clientId: '${{ secrets.CLIENT_ID }}',
                authority: b2cPolicies.authorities.signUpSignIn.authority,
                knownAuthorities: [b2cPolicies.authorityDomain],
                redirectUri: '/'
              }
            },
            apiConfig: {
              scopes: [
                '${{ secrets.SCOPE_READ }}',
                '${{ secrets.SCOPE_WRITE }}'
              ],
              uri: '${{ secrets.BACKEND_URI }}'
            }
          };
          EOL

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DESERT_0ADE3201E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/memoryland" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "dist/memoryland/browser" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_DESERT_0ADE3201E }}
          action: "close"
